config/urls.py
# Todoアプリ
from django.contrib import admin
from django.urls import path, include
 

urlpatterns = [
    # # Todoアプリ
    # path('admin/', admin.site.urls),
    path("todo/", include("todo.urls")),
    
    # ログイン
    path('admin/', admin.site.urls),
    path('', include('login_app.urls'))
]

login_app/urls.py
from . import views
from django.urls import path
from todo.views import TodoCreate

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('', views.login_view, name='login'),
    path('logout/', views.logout_confirm, name='logout_confirm'),
    path('create/', TodoCreate.as_view(), name='todo_create'),
]

todo/urls.py
from django.urls import path
from .views import TodoDetail, TodoList, TodoCreate, TodoUpdate, TodoDelete

urlpatterns = [
    path("todo/", TodoList.as_view(), name="list"),
    path("detail/<int:pk>", TodoDetail.as_view(), name="detail"),
    path("create/", TodoCreate.as_view(), name="create"),
    path("update/<int:pk>", TodoUpdate.as_view(), name="update"),
    path("delete/<int:pk>", TodoDelete.as_view(), name="delete"),  
]

login_app/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField("タスク名", max_length=30)
    description = models.TextField("詳細", blank=True)
    deadline = models.DateField("締め切り")

    
    def __str__(self):
        return self.title
    
    

login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    pass

todo/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'description', 'deadline']
        widgets = {
            'deadline': forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date'}),
        }

login_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import SignupForm, LoginForm
from django.contrib.auth import login, logout
from django.http import JsonResponse
from django.http import HttpResponseRedirect

# Create your views here.
def signup_view(request):
    # POSTかチェック
    if request.method == 'POST':
        # フォームオブジェクトを作成
        form = SignupForm(request.POST)
        # 入力した要件を満たしているかチェック
        if form.is_valid():
            user = form.save()
            # アカウント登録後に自動的にログイン
            login(request, user) 
            # ログインページにリダイレクト
            return redirect(reverse_lazy('login'))
    else:
        # 空のフォームを作成
        form = SignupForm()
    
    # フォームを送信していないとき新規登録ページを表示    
    param = {
        'form': form
    }
    return render(request, 'login_app/signup.html', param)

def login_view(request):
    if request.method == 'POST':
        # ユーザーの入力したデータをフォームに結びつける(バインド)
        form = LoginForm(request, data=request.POST)
        # フォームが有効かチェック
        if form.is_valid():
            user = form.get_user()
            
            if user:
                login(request, user)
                # 'next' パラメータからリダイレクト先を取得
                next_page = request.GET.get('next', reverse_lazy('list'))
                # リダイレクト先を指定してリダイレクト
                return redirect(next_page)
                
    else:
        form = LoginForm()

    param = {
        'form': form,
    }

    return render(request, 'login_app/login.html', param)

from django.urls import reverse
from django.shortcuts import redirect

def logout_confirm(request):
    if request.method == 'POST':
        logout(request)
        # ログイン画面にリダイレクトするために、ログイン画面のURLを解決する
        login_url = reverse('login')
        return HttpResponseRedirect(login_url)
    elif request.method == 'GET':
        return render(request, 'login_app/logout_confirm.html')
    return JsonResponse({'error': 'Only GET and POST methods are allowed'})

def logout_confirm(request):
    if request.method == 'POST':
        logout(request)
        login_url = reverse('login')
        return HttpResponseRedirect(login_url)
    elif request.method == 'GET':
        if 'cancel' in request.GET:
            return redirect(reverse('list'))
        return render(request, 'login_app/logout_confirm.html')
    return JsonResponse({'error': 'Only GET and POST methods are allowed'})

todo/views.py
from django.shortcuts import render 
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
# ユーザーがログインしていることを確認。ログインしていないユーザーがToDoリストにアクセスしようとすると、ログインページにリダイレクトされる。
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Todo
from .forms import TodoForm

class TodoList(LoginRequiredMixin, ListView):
    # このビューで作成するモデルの指定
    model = Todo
    # テンプレート内では、ToDoリストがtasksという名前で利用可能
    context_object_name = "tasks"
    
    def get_queryset(self):
        # ソート順を取得、デフォルトは締め切り昇順
        sort_order = self.request.GET.get('sort', 'deadline_asc')
        if sort_order == 'deadline_desc':
            return Todo.objects.filter(user=self.request.user).order_by('-deadline')
        return Todo.objects.filter(user=self.request.user).order_by('deadline')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_sort'] = self.request.GET.get('sort', 'deadline_asc')
        return context
    
class TodoDetail(LoginRequiredMixin,DetailView):
        model = Todo
        # テンプレート内では、ToDoリストがtaskという名前で利用可能
        context_object_name = "task"
        
class TodoCreate(LoginRequiredMixin, CreateView):
    model = Todo
    # ユーザーに入力させるフィールド指定
    fields = ['title', 'description', 'deadline']
    # Todoが正常に作成された後Listにリダイレクト
    success_url = reverse_lazy('list')
    # ビューで使うテンプレートの名前指定
    template_name = 'todo/todo_form.html'

    def form_valid(self, form):
        # 現在ログインしているユーザーの情報設定
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        # context_dataメソッドの結果をcontextに格納
        context = super().get_context_data(**kwargs)
        # actionキーにcreateを割り当て
        context['action'] = 'create'
        return context
    
class TodoUpdate(LoginRequiredMixin, UpdateView):
    model = Todo
    form_class = TodoForm
    template_name = 'todo/todo_form.html'
    success_url = reverse_lazy('list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'update'
        context['task'] = self.object
        return context
    
class TodoDelete(DeleteView):
    model = Todo
    context_object_name = "task"
    success_url = reverse_lazy("list")
    

login_app/templates/login_app/login.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ログイン</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f8f9fa;
        }
        .login-container {
            width: 100%;
            max-width: 400px; /* 幅を広げる */
            background: white;
            padding: 40px; /* パディングを増やす */
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); /* シャドウを強調 */
        }
        .login-container h1 {
            margin-bottom: 30px; /* マージンを増やす */
            font-size: 1.5em; /* フォントサイズを大きく */
        }
        .btn {
            font-size: 1.2em; /* ボタンのフォントサイズを大きく */
            padding: 10px; /* ボタンのパディングを増やす */
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h1>ログイン</h1>
        <form autocomplete="off" action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group">
                <input type="submit" class="btn btn-primary btn-block" value="ログイン">
            </div>
        </form>
        <button class="btn btn-secondary btn-block" onclick="location.href='https://simpletodoapp.azurewebsites.net/signup/'">新規登録</button>
    </div>
    <!-- Bootstrap JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

login_app/templates/login_app/logout_confirm.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログアウト確認</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- Logout Modal -->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="logoutModalLabel">ログアウトしますか？</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'logout_confirm' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">ログアウト</button>
                    </form>
                    <button id="cancel-button" type="button" class="btn btn-secondary">キャンセル</button>
                </div>
            </div>
        </div>
    </div>

    <!-- JavaScript to show the modal -->
    <script>
        $(document).ready(function(){
            $('#logoutModal').modal('show');

            // Add event listener to the cancel button
            $('#cancel-button').on('click', function() {
                window.location.href = "{% url 'list' %}";
            });
        });
    </script>
</body>
</html>

login_app/templates/login_app/signup.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ユーザー登録</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f8f9fa;
        }
        .signup-container {
            width: 100%;
            max-width: 500px;
            background: white;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }
        .signup-container h1 {
            margin-bottom: 30px;
            font-size: 1.8em;
            text-align: center;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .btn {
            font-size: 1.2em;
            padding: 10px;
        }
        .form-control {
            height: calc(2.25rem + 10px);
            padding: 10px;
            font-size: 1em;
        }
        .errorlist {
            color: red;
            margin-top: 5px;
            margin-bottom: 0;
        }
        .condition {
            margin-top: 10px;
            font-size: 0.9em;
            color: #dc3545; /* Bootstrap のエラーカラーに合わせる */
        }
    </style>
</head>
<body>
    <div class="signup-container">
        <h1>ユーザー登録</h1>
        <form autocomplete="off" action="{% url 'signup' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">ユーザー名</label>
                {{ form.username }}
                {% if form.username.errors %}
                    <ul class="errorlist">
                        {% for error in form.username.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_password1">パスワード</label>
                {{ form.password1 }}
                {% if form.password1.errors %}
                    <ul class="errorlist">
                        {% for error in form.password1.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <p class="condition">
                    パスワードは最低8文字以上必要です。<br>
                    数字だけのパスワードは使えません。
                </p>
            </div>
            <div class="form-group">
                <label for="id_password2">パスワード確認</label>
                {{ form.password2 }}
                {% if form.password2.errors %}
                    <ul class="errorlist">
                        {% for error in form.password2.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary btn-block" value="登録">
            </div>
        </form>
    </div>
    <!-- Bootstrap JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>


todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet">
    <style>
        body{
            padding-top: 20px;
            font-family: 'Open Sans', sans-serif;
        }
        #sortOrder.form-select {
            width: auto; 
            max-width: 150px; 
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="w-75 mx-auto">
            <div class="shadow-sm p-3 mb-5 bg-white rounded">
                {% block header %}
                {% endblock header %}
            </div>

            {% block content %}
            {% endblock content %}
        </div>
      </div>
</body>
</html>

todo/templates/todo/todo_confirm_delete.html
{% extends 'todo/base.html' %}

{% block header %}
<h1>タスクの削除</h1>
{% endblock header %}

{% block content %}
<p>「{{task.title}}」を削除しますか？</p>
<form action="" method="POST">{% csrf_token %}
    <a class="btn btn-outline-secondary" href="{% url 'list' %}" role="button">戻る</a>
    <input class="btn btn-danger" type="submit" value="削除">
</form>
{% endblock content %}

todo/templates/todo/todo_detail.html
{% extends 'todo/base.html' %}

{% block header %}
<h1>タスクの詳細</h1>
{% endblock header %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h2>{{task.title}}</h2>
        <p>{{ task.description|linebreaksbr }}</p>
        <p><small class="text-muted">{{task.deadline}}</small></p>
    </div>
</div>
<a class="btn btn-outline-secondary mt-2" href="{% url 'list' %}" role="button">戻る</a>
<a class="btn btn-success mt-2" href="{% url 'update' task.pk %}" role="button">編集</a>
{% endblock content %}

todo/templates/todo/todo_form.html
{% extends 'todo/base.html' %}

{% block header %}
{% if action == 'create' %}
<h1>タスクの作成</h1>
{% elif action == 'update' %}
<h1>タスクの編集</h1>
{% endif %}
{% endblock header %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <table class="table">
        <tbody>
            <tr>
                <th>
                    <label for="id_title">タスク名:</label>
                </th>
                <td>
                    <input type="text" name="title" maxlength="15" required id="id_title" value="{{ form.title.value|default_if_none:'' }}">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_description">内容:</label>
                </th>
                <td>
                    <textarea name="description" cols="40" rows="10" id="id_description">{{ form.description.value|default_if_none:'' }}</textarea>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_deadline">締め切り:</label>
                </th>
                <td>
                    <input type="date" name="deadline" required id="id_deadline" value="{{ form.deadline.value|date:'Y-m-d' }}">
                </td>
            </tr>
        </tbody>
    </table>
    <a class="btn btn-outline-secondary" href="{% url 'list' %}" role="button">戻る</a>
    <input class="btn btn-success" type="submit" value="{% if action == 'create' %}作成{% elif action == 'update' %}更新{% endif %}">
</form>
{% endblock content %}

todo/templates/todo/todo_list.html
{% extends 'todo/base.html' %}

{% block header %}
<h1>Todo list</h1>
<p><a href="{% url 'create' %}">新規作成</a></p>
<p><a href="{% url 'logout_confirm' %}">ログアウト</a></p>
{% endblock header %}

{% block content %}
<div class="mb-3">
    <label for="sortOrder" class="form-label">表示順</label>
    <select id="sortOrder" class="form-select" onchange="location = this.value;">
        <option value="?sort=deadline_asc" {% if current_sort == 'deadline_asc' %}selected{% endif %}>昇順</option>
        <option value="?sort=deadline_desc" {% if current_sort == 'deadline_desc' %}selected{% endif %}>降順</option>
    </select>
</div>

<div class="shadow-sm p-3 mb-5 bg-white rounded">
    <style>
        .table th {
            text-align: center;
        }
    </style>
    <table class="table table-bordered" style="width: 100%;">
        <thead>
            <tr>
                <th scope="col">タスク名</th>
                <th scope="col">締め切り</th>
                <th scope="col">内容</th>
                <th scope="col">操作</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>{{task.title}}</td>
                <td>{{task.deadline}}</td>
                <td class="ellipsis">{{task.description}}</td>
                <td>
                    <a href="{% url 'detail' task.pk %}">詳細</a> |
                    <a href="{% url 'update' task.pk %}">編集</a> |
                    <a href="{% url 'delete' task.pk %}">削除</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const maxLength = 20; // 省略する文字数を設定
        const ellipsisElements = document.querySelectorAll('.ellipsis');

        ellipsisElements.forEach(function(element) {
            if (element.textContent.length > maxLength) {
                element.textContent = element.textContent.substring(0, maxLength) + '...';
            }
        });
    });
</script>
{% endblock content %}